import { Toaster } from "react-hot-toast";
import Providers from "../providers";
import "../globals.css";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
    // manifest: "../manifest.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Providers>
          <Toaster />
          <Header />
          {children}
        </Providers>
        <Footer/>
      </body>
    </html>
  );
}
